SLIDE_iter: 500
SLIDE_top_feats: 10
delta:
- 0.05
- 0.1
- 0.2
do_interacts: true
eval_type: corr
fdr: 0.2
lambda:
- 0.1
- 0.5
- 1.0
n_workers: 4
out_path: /ix/djishnu/Aaron/1_general_use/SLIDE_py/comparison/output_comparison/2026-01-16_10-41-07/SSc_continuous_comparison/Py_pyLOVE_rKO
pure_homo: true
sampleCV_iter: 500
spec: 0.1
thresh_fdr: 0.2
x_path: /ix/djishnu/Aaron/1_general_use/SLIDE/Data_Scripts/SSc/UnTx/X.csv
y_factor: false
y_path: /ix/djishnu/Aaron/1_general_use/SLIDE/Data_Scripts/SSc/UnTx/Y.csv
