x_path: /ix/djishnu/Aaron/0_for_others/Crystal/SLIDE/Scleroderma_Control/Scleroderma_Control_x_filtered.csv
y_path: /ix/djishnu/Aaron/0_for_others/Crystal/SLIDE/Scleroderma_Control/Scleroderma_Control_y.csv
out_path: /ix/djishnu/Aaron/1_general_use/SLIDE_py/comparison/output_comparison/2026-01-16_10-32-33/SSc_binary_comparison/R_native
delta:
- 0.05
- 0.1
- 0.2
lambda:
- 0.1
- 0.5
- 1.0
spec: 0.1
fdr: 0.2
SLIDE_iter: 500
thresh_fdr: 0.2
eval_type: auc
y_factor: yes
do_interacts: yes
pure_homo: yes
SLIDE_top_feats: 10
sampleCV_iter: 500
n_workers: 4
